version: "3.9"
services:
  goweb:
    image: da43c2886538
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT
      - MODELGPT
      - GPTURL
      - KEYS
      - RESPTIME
      - TEST
      - TESTTEXT
  pyweb:
    image: 7436e623a251
    ports:
      - "50051:50051"