version: "3.9"
services:
  goweb:
    image: 2aaba1e434fe
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT
      - MODELGPT
      - GPTURL
      - KEYPATH
  pyweb:
    image: 7436e623a251
    ports:
      - "${PORT2PY}:${PORT2PY}"