version: "3.9"
services:
  goweb:
    image: 9a20dc32ce415bdb99ec8fff036b5d482395b7ed07415de880b254f6c232413e
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT
      - MODELGPT
      - GPTURL
      - KEYS
  pyweb:
    image: 7436e623a251
    ports:
      - "50051:50051"