version: "3.9"
services:
  goweb:
    image: d7cce2b60c4d
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT
      - MODELGPT
      - GPTURL
      - KEYS
      - RESPTIME
      - TEST
  pyweb:
    image: 7436e623a251
    ports:
      - "50051:50051"